// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Spread struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Version        int32              `json:"version"`
	Ectm           pgtype.Int4        `json:"ectm"`
	Pages          json.RawMessage    `json:"pages"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
}
