// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snaps.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSnap = `-- name: CreateSnap :one
INSERT INTO snaps (
    id,
    spread_id,
    spread_version,
    edition,
    schema,
    published_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING
    id,
    spread_id,
    spread_version,
    edition,
    schema,
    published_at
`

type CreateSnapParams struct {
	ID            pgtype.UUID        `json:"id"`
	SpreadID      pgtype.UUID        `json:"spread_id"`
	SpreadVersion int32              `json:"spread_version"`
	Edition       int32              `json:"edition"`
	Schema        json.RawMessage    `json:"schema"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

type CreateSnapRow struct {
	ID            pgtype.UUID        `json:"id"`
	SpreadID      pgtype.UUID        `json:"spread_id"`
	SpreadVersion int32              `json:"spread_version"`
	Edition       int32              `json:"edition"`
	Schema        json.RawMessage    `json:"schema"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateSnap(ctx context.Context, arg CreateSnapParams) (CreateSnapRow, error) {
	row := q.db.QueryRow(ctx, createSnap,
		arg.ID,
		arg.SpreadID,
		arg.SpreadVersion,
		arg.Edition,
		arg.Schema,
		arg.PublishedAt,
	)
	var i CreateSnapRow
	err := row.Scan(
		&i.ID,
		&i.SpreadID,
		&i.SpreadVersion,
		&i.Edition,
		&i.Schema,
		&i.PublishedAt,
	)
	return i, err
}

const deleteSnap = `-- name: DeleteSnap :execrows
UPDATE snaps
SET closed_at = NOW()
WHERE id = $1
AND closed_at IS NULL
`

func (q *Queries) DeleteSnap(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSnap, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSnap = `-- name: GetSnap :one
SELECT
    id,
    spread_id,
    spread_version,
    edition,
    schema,
    published_at
FROM snaps
WHERE id = $1
AND closed_at IS NULL
`

type GetSnapRow struct {
	ID            pgtype.UUID        `json:"id"`
	SpreadID      pgtype.UUID        `json:"spread_id"`
	SpreadVersion int32              `json:"spread_version"`
	Edition       int32              `json:"edition"`
	Schema        json.RawMessage    `json:"schema"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetSnap(ctx context.Context, id pgtype.UUID) (GetSnapRow, error) {
	row := q.db.QueryRow(ctx, getSnap, id)
	var i GetSnapRow
	err := row.Scan(
		&i.ID,
		&i.SpreadID,
		&i.SpreadVersion,
		&i.Edition,
		&i.Schema,
		&i.PublishedAt,
	)
	return i, err
}

const latestEdition = `-- name: LatestEdition :one
SELECT
    edition
FROM snaps
WHERE spread_id = $1
ORDER BY edition DESC
LIMIT 1
`

func (q *Queries) LatestEdition(ctx context.Context, spreadID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, latestEdition, spreadID)
	var edition int32
	err := row.Scan(&edition)
	return edition, err
}

const listSnapMetaData = `-- name: ListSnapMetaData :many
SELECT
    id,
    spread_id,
    spread_version,
    schema,
    edition,
    published_at
FROM snaps
WHERE closed_at IS NULL
ORDER BY published_at DESC
`

type ListSnapMetaDataRow struct {
	ID            pgtype.UUID        `json:"id"`
	SpreadID      pgtype.UUID        `json:"spread_id"`
	SpreadVersion int32              `json:"spread_version"`
	Schema        json.RawMessage    `json:"schema"`
	Edition       int32              `json:"edition"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListSnapMetaData(ctx context.Context) ([]ListSnapMetaDataRow, error) {
	rows, err := q.db.Query(ctx, listSnapMetaData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnapMetaDataRow{}
	for rows.Next() {
		var i ListSnapMetaDataRow
		if err := rows.Scan(
			&i.ID,
			&i.SpreadID,
			&i.SpreadVersion,
			&i.Schema,
			&i.Edition,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapMetaDataBySpreadId = `-- name: ListSnapMetaDataBySpreadId :many
SELECT
    id,
    spread_id,
    spread_version,
    schema,
    edition,
    published_at
FROM snaps
WHERE spread_id = $1
AND closed_at IS NULL
ORDER BY edition DESC
`

type ListSnapMetaDataBySpreadIdRow struct {
	ID            pgtype.UUID        `json:"id"`
	SpreadID      pgtype.UUID        `json:"spread_id"`
	SpreadVersion int32              `json:"spread_version"`
	Schema        json.RawMessage    `json:"schema"`
	Edition       int32              `json:"edition"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListSnapMetaDataBySpreadId(ctx context.Context, spreadID pgtype.UUID) ([]ListSnapMetaDataBySpreadIdRow, error) {
	rows, err := q.db.Query(ctx, listSnapMetaDataBySpreadId, spreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnapMetaDataBySpreadIdRow{}
	for rows.Next() {
		var i ListSnapMetaDataBySpreadIdRow
		if err := rows.Scan(
			&i.ID,
			&i.SpreadID,
			&i.SpreadVersion,
			&i.Schema,
			&i.Edition,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nullSpreadId = `-- name: NullSpreadId :execrows
UPDATE snaps
SET spread_id = NULL
WHERE spread_id = $1
`

func (q *Queries) NullSpreadId(ctx context.Context, spreadID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, nullSpreadId, spreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
