// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spills.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpill = `-- name: CreateSpill :one
INSERT INTO spills(
    id,
    snap_id,
    first_name,
    last_name,
    email,
    r_schema
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING
    id,
    snap_id,
    first_name,
    last_name,
    email,
    created_at,
    last_modified_at,
    completed_at,
    sent_at,
    expired_at
`

type CreateSpillParams struct {
	ID        pgtype.UUID `json:"id"`
	SnapID    pgtype.UUID `json:"snap_id"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Email     string      `json:"email"`
	RSchema   []byte      `json:"r_schema"`
}

type CreateSpillRow struct {
	ID             pgtype.UUID        `json:"id"`
	SnapID         pgtype.UUID        `json:"snap_id"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Email          string             `json:"email"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	ExpiredAt      pgtype.Timestamptz `json:"expired_at"`
}

func (q *Queries) CreateSpill(ctx context.Context, arg CreateSpillParams) (CreateSpillRow, error) {
	row := q.db.QueryRow(ctx, createSpill,
		arg.ID,
		arg.SnapID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.RSchema,
	)
	var i CreateSpillRow
	err := row.Scan(
		&i.ID,
		&i.SnapID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.CompletedAt,
		&i.SentAt,
		&i.ExpiredAt,
	)
	return i, err
}

const deleteSpill = `-- name: DeleteSpill :execrows
DELETE FROM spills
WHERE id = $1
`

func (q *Queries) DeleteSpill(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpill, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSpillMetaDataBySnapId = `-- name: ListSpillMetaDataBySnapId :many
SELECT
    id,
    snap_id,
    first_name,
    last_name,
    email,
    created_at,
    last_modified_at,
    completed_at,
    sent_at,
    expired_at
FROM spills
WHERE snap_id = $1
ORDER BY last_modified_at DESC
`

type ListSpillMetaDataBySnapIdRow struct {
	ID             pgtype.UUID        `json:"id"`
	SnapID         pgtype.UUID        `json:"snap_id"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	Email          string             `json:"email"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	ExpiredAt      pgtype.Timestamptz `json:"expired_at"`
}

func (q *Queries) ListSpillMetaDataBySnapId(ctx context.Context, snapID pgtype.UUID) ([]ListSpillMetaDataBySnapIdRow, error) {
	rows, err := q.db.Query(ctx, listSpillMetaDataBySnapId, snapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpillMetaDataBySnapIdRow{}
	for rows.Next() {
		var i ListSpillMetaDataBySnapIdRow
		if err := rows.Scan(
			&i.ID,
			&i.SnapID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.CreatedAt,
			&i.LastModifiedAt,
			&i.CompletedAt,
			&i.SentAt,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
