// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spreads.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpread = `-- name: CreateSpread :one
INSERT INTO spreads (
    id,
    spread_title,
    schema
) VALUES (
    $1, $2, $3
)
RETURNING
    id,
    spread_title,
    version,
    schema,
    created_at,
    last_modified_at
`

type CreateSpreadParams struct {
	ID          pgtype.UUID     `json:"id"`
	SpreadTitle string          `json:"spread_title"`
	Schema      json.RawMessage `json:"schema"`
}

func (q *Queries) CreateSpread(ctx context.Context, arg CreateSpreadParams) (Spread, error) {
	row := q.db.QueryRow(ctx, createSpread, arg.ID, arg.SpreadTitle, arg.Schema)
	var i Spread
	err := row.Scan(
		&i.ID,
		&i.SpreadTitle,
		&i.Version,
		&i.Schema,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}

const deleteSpread = `-- name: DeleteSpread :execrows
DELETE FROM spreads
WHERE id = $1
`

func (q *Queries) DeleteSpread(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpread, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCountBySpreadTitle = `-- name: GetCountBySpreadTitle :one
SELECT
COUNT(*)
FROM spreads
WHERE spread_title = $1
`

func (q *Queries) GetCountBySpreadTitle(ctx context.Context, spreadTitle string) (int64, error) {
	row := q.db.QueryRow(ctx, getCountBySpreadTitle, spreadTitle)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCountBySpreadTitleExcludingId = `-- name: GetCountBySpreadTitleExcludingId :one
SELECT
COUNT(*)
FROM spreads
WHERE spread_title = $1
AND id <> $2
`

type GetCountBySpreadTitleExcludingIdParams struct {
	SpreadTitle string      `json:"spread_title"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetCountBySpreadTitleExcludingId(ctx context.Context, arg GetCountBySpreadTitleExcludingIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCountBySpreadTitleExcludingId, arg.SpreadTitle, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSpread = `-- name: GetSpread :one
SELECT
    id,
    spread_title,
    version,
    schema,
    created_at,
    last_modified_at
FROM spreads
WHERE id = $1
`

func (q *Queries) GetSpread(ctx context.Context, id pgtype.UUID) (Spread, error) {
	row := q.db.QueryRow(ctx, getSpread, id)
	var i Spread
	err := row.Scan(
		&i.ID,
		&i.SpreadTitle,
		&i.Version,
		&i.Schema,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}

const getSpreadVersion = `-- name: GetSpreadVersion :one
SELECT version
FROM spreads
WHERE id = $1
`

func (q *Queries) GetSpreadVersion(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getSpreadVersion, id)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const listSpreadMetaData = `-- name: ListSpreadMetaData :many
SELECT
    id,
    spread_title,
    created_at,
    last_modified_at
FROM spreads
ORDER BY created_at DESC
`

type ListSpreadMetaDataRow struct {
	ID             pgtype.UUID        `json:"id"`
	SpreadTitle    string             `json:"spread_title"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
}

func (q *Queries) ListSpreadMetaData(ctx context.Context) ([]ListSpreadMetaDataRow, error) {
	rows, err := q.db.Query(ctx, listSpreadMetaData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpreadMetaDataRow{}
	for rows.Next() {
		var i ListSpreadMetaDataRow
		if err := rows.Scan(
			&i.ID,
			&i.SpreadTitle,
			&i.CreatedAt,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpread = `-- name: UpdateSpread :one
UPDATE spreads
SET
    spread_title = $2,
    schema = $3,
    version = version + 1,
    last_modified_at = NOW()
WHERE id = $1 AND version = $4
RETURNING
    id,
    spread_title,
    version,
    schema,
    created_at,
    last_modified_at
`

type UpdateSpreadParams struct {
	ID          pgtype.UUID     `json:"id"`
	SpreadTitle string          `json:"spread_title"`
	Schema      json.RawMessage `json:"schema"`
	Version     int32           `json:"version"`
}

func (q *Queries) UpdateSpread(ctx context.Context, arg UpdateSpreadParams) (Spread, error) {
	row := q.db.QueryRow(ctx, updateSpread,
		arg.ID,
		arg.SpreadTitle,
		arg.Schema,
		arg.Version,
	)
	var i Spread
	err := row.Scan(
		&i.ID,
		&i.SpreadTitle,
		&i.Version,
		&i.Schema,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}
