// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spreads.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpread = `-- name: CreateSpread :one
INSERT INTO spreads (
    id,
    title,
    version,
    ectm,
    pages,
    created_at,
    last_modified_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING
    id,
    title,
    version,
    ectm,
    pages,
    created_at,
    last_modified_at
`

type CreateSpreadParams struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Version        int32              `json:"version"`
	Ectm           pgtype.Int4        `json:"ectm"`
	Pages          json.RawMessage    `json:"pages"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
}

func (q *Queries) CreateSpread(ctx context.Context, arg CreateSpreadParams) (Spread, error) {
	row := q.db.QueryRow(ctx, createSpread,
		arg.ID,
		arg.Title,
		arg.Version,
		arg.Ectm,
		arg.Pages,
		arg.CreatedAt,
		arg.LastModifiedAt,
	)
	var i Spread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Version,
		&i.Ectm,
		&i.Pages,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}

const deleteSpread = `-- name: DeleteSpread :execrows
DELETE FROM spreads
WHERE id = $1
`

func (q *Queries) DeleteSpread(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpread, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSpread = `-- name: GetSpread :one
SELECT
    id,
    title,
    version,
    ectm,
    pages,
    created_at,
    last_modified_at
FROM spreads
WHERE id = $1
`

func (q *Queries) GetSpread(ctx context.Context, id pgtype.UUID) (Spread, error) {
	row := q.db.QueryRow(ctx, getSpread, id)
	var i Spread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Version,
		&i.Ectm,
		&i.Pages,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}

const getSpreadVersion = `-- name: GetSpreadVersion :one
SELECT version
FROM spreads
WHERE id = $1
`

func (q *Queries) GetSpreadVersion(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getSpreadVersion, id)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const listSpreadMetaData = `-- name: ListSpreadMetaData :many
SELECT
    id,
    title,
    created_at,
    last_modified_at
FROM spreads
ORDER BY last_modified_at DESC
`

type ListSpreadMetaDataRow struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
}

func (q *Queries) ListSpreadMetaData(ctx context.Context) ([]ListSpreadMetaDataRow, error) {
	rows, err := q.db.Query(ctx, listSpreadMetaData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpreadMetaDataRow{}
	for rows.Next() {
		var i ListSpreadMetaDataRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpread = `-- name: UpdateSpread :one
UPDATE spreads
SET
    title = $2,
    ectm = $3,
    pages = $4,
    version = version + 1,
    last_modified_at = NOW()
WHERE id = $1 AND version = $5
RETURNING
    id,
    title,
    version,
    ectm,
    pages,
    created_at,
    last_modified_at
`

type UpdateSpreadParams struct {
	ID      pgtype.UUID     `json:"id"`
	Title   string          `json:"title"`
	Ectm    pgtype.Int4     `json:"ectm"`
	Pages   json.RawMessage `json:"pages"`
	Version int32           `json:"version"`
}

func (q *Queries) UpdateSpread(ctx context.Context, arg UpdateSpreadParams) (Spread, error) {
	row := q.db.QueryRow(ctx, updateSpread,
		arg.ID,
		arg.Title,
		arg.Ectm,
		arg.Pages,
		arg.Version,
	)
	var i Spread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Version,
		&i.Ectm,
		&i.Pages,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}
